### PR TITLE
Add isCompanyDomain validator

### PR DESCRIPTION
**Pull request by tandrewnichols**
Installing generated a package-lock file. Should I check that in?

### CODE REVIEW

**Comment by bnurbekov** [comment]
No, I think that there is no need to commit it, since it’s a library: https://www.twilio.com/blog/lockfiles-nodejs
Please could you also add the function signature in index.d.ts?

**Comment by tandrewnichols** [comment]
@bnurbekov Done

**Comment by tandrewnichols** [comment]
Looks like this was published in 1.0.6?

I discovered I did not update the README as part of this. Sorry, that was an oversight on my part.

**Comment by bnurbekov** [comment]
Hi @tandrewnichols , no problem at all. I was going to add some examples into README, but didn’t get a chance yet.

**Pull request merged**
